Return txhash from aggregator and display in Quill
jzaki/bls-wallet pull request #369
Opened 2022-11-01 14:45 UTC by blakecduncan

## What is this PR doing?
- Return txhash from aggregator and display in Quill

## How can these changes be manually tested?
- Execute a tx in Quill and view transaction hash in the transactions table

## Does this PR resolve or contribute to any issues?
https://github.com/web3well/bls-wallet/issues/329

## Checklist
- [x] I have manually tested these changes
- [x] Post a link to the PR in the group chat

## Guidelines
- If your PR is not ready, mark it as a draft
- The `resolve conversation` button is for reviewers, not authors
  - (But add a 'done' comment or similar)

2022-11-02 08:48 UTC, blakecduncan commented on extension/source/background/AggregatorController.ts
> +      await this.InternalRpc().updateTransactionBundleHash(
Need to set the bundle hash on the tx so that when we later call get bundle receipt we can link the transaction with the receipt

2022-11-02 08:48 UTC, blakecduncan commented on extension/source/background/AggregatorController.ts
> +          transactionHash: bundleReceipt.transactionHash,
do we want to add a `bundleHash` value here?

2022-11-02 08:48 UTC, blakecduncan commented on aggregator/src/app/BundleService.ts
> +      bundleHash: hash,
My understanding is that the `transactionHash` is the hash of the transaction on chain.  I also wanted to return `bundleHash` because that is the hash we use to identify the bundle in the aggregator db.  Feel free to let me know if my understanding is wrong or if I should change this

2022-11-03 06:32 UTC, voltrevo commented on extension/source/background/AggregatorController.ts
> +          transactionHash: bundleReceipt.transactionHash,
Maybe, but I wouldn't do it proactively since `eth_getTransactionReceipt` has a standard structure

2022-11-03 06:34 UTC, voltrevo commented on aggregator/src/app/BundleService.ts
> +      bundleHash: hash,
Sounds right. Notably, the 'transaction' of `transactionHash` is the `processBundle` call rather than the user's transaction (aka operation) inside.

2022-11-03 06:36 UTC, voltrevo commented on extension/source/Home/Wallet/Wallets/TransactionsTable.tsx
>          window.open(`https://etherscan.io/tx/${cell.getValue()}`),
Followup: https://github.com/web3well/bls-wallet/issues/372

2022-11-03 06:37 UTC, voltrevo approved these changes

2022-11-03 07:11 UTC, kautukkundan requested changes
Tested on Goerli - 
1. Doing single action tx from a dapp did not show up in the transactions table even though the entries were created in the localstorage ❌
2. Doing a multi action tx correctly populates the transactions table ✅
3. Sending ETH from within the extension correctly populates the transactions table ✅
4. Did not test recovery ❓

used the erc20 demo app for the purpose - 
https://joyful-semifreddo-3b0769.netlify.app/

Could you please verify (and fix if true)

2022-11-03 10:30 UTC, blakecduncan commented
> Tested on Goerli -
> 
> 1. Doing single action tx from a dapp did not show up in the transactions table even though the entries were created in the localstorage ❌
> 2. Doing a multi action tx correctly populates the transactions table ✅
> 3. Sending ETH from within the extension correctly populates the transactions table ✅
> 4. Did not test recovery ❓

@kautukkundan sorry I missed the single action.  That should be fixed now.  As Andrew mentioned in the discord channel, the filtering on the transaction table was case-sensitive.  I haven't dug in enough to know why sometimes the addresses have mixed case and other times they don't.  Maybe it has something to do with the network?  I'll take a deeper look but I don't think the mixed case is related to this PR.

For recovery, that code isn't merged into main yet so I haven't tested it.  However, I don't think the way we set it up it would show up in the transactions table.  Main reason being is that we are using a temporary wallet to execute the recovery user op.  So there's nowhere for us to visualize the tx.

2022-11-03 10:55 UTC, kautukkundan approved these changes
Gotcha, maybe something to look into in the future. 
could use checksum -
https://docs.ethers.io/v5/api/utils/address/#utils-getAddress

but LGTM for now 🚢

2022-11-03 13:37 UTC, merged