Update local and remote docs
jzaki/bls-wallet pull request #591
Opened 2023-04-27 16:44 UTC by ri-dev-git

## What is this PR doing?
Addition of setup steps for #501.

## How can these changes be manually tested?

## Does this PR resolve or contribute to any issues?
yes, #501

## Checklist
- [ ] I have manually tested these changes
- [ ] Post a link to the PR in the group chat

## Guidelines
- If your PR is not ready, mark it as a draft
- The `resolve conversation` button is for reviewers, not authors
  - (But add a 'done' comment or similar)

2023-04-27 17:15 UTC, JohnGuilding requested changes
Thanks for doing this @ri-dev-git!

Left a few suggestions

2023-04-27 17:15 UTC, JohnGuilding commented on docs/local_development.md
> +4. Transfer eth from metamask to Quill if using `yarn start-hardhat` in `./contracts`.
```suggestion
4. Transfer ETH from a funded account to Quill - e.g. an imported MetaMask account
```

You can fund the account in multiple ways beyond metamask, for example, a script. So could make the suggestion broader and add metamask as an example.

2023-04-27 17:15 UTC, JohnGuilding commented on docs/local_development.md
> +> **.env.local.example** for **local**
> **.env.local.example** for **local**

I'd say you could remove this line, as it is stated in the code example above. Feel free to disagree!

2023-04-27 17:15 UTC, JohnGuilding commented on docs/local_development.md
>  ### Firefox
Could you add the same point to the firefox instructions too?

e.g. `4. Transfer ETH from a funded account to Quill - e.g. an imported MetaMask account`

2023-04-27 17:15 UTC, JohnGuilding commented on docs/remote_development.md
> +> **.env.example** for **remote**
Same comment as above, could remove this line. 

I can see that there is no code example here for copying .env.example. Could you add this snippet above like this?

___
_The [aggregator](../aggregator/) is a service that accepts transaction bundles (including those that contain a single transaction) and submits aggregations of these bundles to L2.

```sh
cd ./aggregator
cp .env.example .env
```


Update the following values in `./aggregator/.env`
___

2023-04-28 11:03 UTC, ri-dev-git commented
Hi @JohnGuilding! I have made the changes please checkI

2023-04-28 21:40 UTC, JohnGuilding commented on docs/remote_development.md
> +> **Note: This .env file now uses `arbitrum` RPCs.**
Could you remove this comment and the whitespace below it? Don't think it's needed as arbitrum is mentioned above and you can see the arbitrum goerli rpcs in the .env file

2023-04-28 21:40 UTC, JohnGuilding commented
@ri-dev-git one final comment then we're ready to merge!

2023-04-29 06:14 UTC, ri-dev-git commented
HI @JohnGuilding! Done with it!

2023-04-29 07:20 UTC, JohnGuilding approved these changes
Looks good! Awesome thanks for doing this @ri-dev-git

2023-04-29 07:21 UTC, merged

2023-04-29 07:26 UTC, JohnGuilding commented
@ri-dev-git now that you've got your windows setup sorted, feel free to pick up another issue if you want to start writing  some code, as I know you haven't done much of that yet 🙂

Check out issues marked as [a good first issue](https://github.com/web3well/bls-wallet/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)